// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.2
// source: src/prism-proto/proto/meta.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MetaServiceClient is the client API for MetaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetaServiceClient interface {
	GetTableSchema(ctx context.Context, in *GetTableSchemaRequest, opts ...grpc.CallOption) (*GetTableSchemaResponse, error)
	GetTablePartitions(ctx context.Context, in *GetTablePartitionsRequest, opts ...grpc.CallOption) (*GetTablePartitionsResponse, error)
	RecordNewPartition(ctx context.Context, in *RecordNewPartitionRequest, opts ...grpc.CallOption) (*RecordNewPartitionResponse, error)
}

type metaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetaServiceClient(cc grpc.ClientConnInterface) MetaServiceClient {
	return &metaServiceClient{cc}
}

func (c *metaServiceClient) GetTableSchema(ctx context.Context, in *GetTableSchemaRequest, opts ...grpc.CallOption) (*GetTableSchemaResponse, error) {
	out := new(GetTableSchemaResponse)
	err := c.cc.Invoke(ctx, "/prism.meta.v1.MetaService/GetTableSchema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaServiceClient) GetTablePartitions(ctx context.Context, in *GetTablePartitionsRequest, opts ...grpc.CallOption) (*GetTablePartitionsResponse, error) {
	out := new(GetTablePartitionsResponse)
	err := c.cc.Invoke(ctx, "/prism.meta.v1.MetaService/GetTablePartitions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaServiceClient) RecordNewPartition(ctx context.Context, in *RecordNewPartitionRequest, opts ...grpc.CallOption) (*RecordNewPartitionResponse, error) {
	out := new(RecordNewPartitionResponse)
	err := c.cc.Invoke(ctx, "/prism.meta.v1.MetaService/RecordNewPartition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaServiceServer is the server API for MetaService service.
// All implementations must embed UnimplementedMetaServiceServer
// for forward compatibility
type MetaServiceServer interface {
	GetTableSchema(context.Context, *GetTableSchemaRequest) (*GetTableSchemaResponse, error)
	GetTablePartitions(context.Context, *GetTablePartitionsRequest) (*GetTablePartitionsResponse, error)
	RecordNewPartition(context.Context, *RecordNewPartitionRequest) (*RecordNewPartitionResponse, error)
	mustEmbedUnimplementedMetaServiceServer()
}

// UnimplementedMetaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMetaServiceServer struct {
}

func (UnimplementedMetaServiceServer) GetTableSchema(context.Context, *GetTableSchemaRequest) (*GetTableSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTableSchema not implemented")
}
func (UnimplementedMetaServiceServer) GetTablePartitions(context.Context, *GetTablePartitionsRequest) (*GetTablePartitionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTablePartitions not implemented")
}
func (UnimplementedMetaServiceServer) RecordNewPartition(context.Context, *RecordNewPartitionRequest) (*RecordNewPartitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordNewPartition not implemented")
}
func (UnimplementedMetaServiceServer) mustEmbedUnimplementedMetaServiceServer() {}

// UnsafeMetaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetaServiceServer will
// result in compilation errors.
type UnsafeMetaServiceServer interface {
	mustEmbedUnimplementedMetaServiceServer()
}

func RegisterMetaServiceServer(s grpc.ServiceRegistrar, srv MetaServiceServer) {
	s.RegisterService(&MetaService_ServiceDesc, srv)
}

func _MetaService_GetTableSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).GetTableSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prism.meta.v1.MetaService/GetTableSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).GetTableSchema(ctx, req.(*GetTableSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaService_GetTablePartitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTablePartitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).GetTablePartitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prism.meta.v1.MetaService/GetTablePartitions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).GetTablePartitions(ctx, req.(*GetTablePartitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaService_RecordNewPartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordNewPartitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).RecordNewPartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prism.meta.v1.MetaService/RecordNewPartition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).RecordNewPartition(ctx, req.(*RecordNewPartitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetaService_ServiceDesc is the grpc.ServiceDesc for MetaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "prism.meta.v1.MetaService",
	HandlerType: (*MetaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTableSchema",
			Handler:    _MetaService_GetTableSchema_Handler,
		},
		{
			MethodName: "GetTablePartitions",
			Handler:    _MetaService_GetTablePartitions_Handler,
		},
		{
			MethodName: "RecordNewPartition",
			Handler:    _MetaService_RecordNewPartition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/prism-proto/proto/meta.proto",
}
